{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://api.cluster.dyte.in/v2",
      "description": "",
      "variables": {}
    }
  ],
  "info": {
    "version": "v2",
    "title": "Dyte v2 Collection",
    "description": "Next generation APIs",
    "termsOfService": "",
    "contact": {},
    "license": {
      "name": ""
    }
  },
  "paths": {
    "/livestreams": {
      "post": {
        "summary": "Create a LiveStream",
        "description": "Create a live stream\n",
        "operationId": "StartaLiveStream",
        "parameters": [
          {
            "$ref": "#/components/parameters/Content-Type"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {
                    "value": {}
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "description": "Create a live stream\n",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "string",
                "example": "testing"
              },
              "example": "{\n    \"name\": \"testing\"\n}"
            }
          }
        },
        "tags": [
          "LiveStreams"
        ]
      },
      "get": {
        "summary": "Get all LiveStreams",
        "description": "Get all live streams created by an organization\n",
        "operationId": "GetallLiveStreams",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "success": true,
                      "message": "",
                      "data": {
                        "limit": 10,
                        "total": 1,
                        "totalCount": 1,
                        "pageCount": 1,
                        "currentPage": 1,
                        "livestreams": [
                          {
                            "id": "850340555635017830461318",
                            "title": "testing",
                            "input_rtmp_url": "rtmp://livestreaming.dyte.io/LiveApp/850340555635017830461318?token=502603528024515256366542",
                            "token_id": "502603528024515256366542",
                            "stream_key": "850340555635017830461318?token=502603528024515256366542",
                            "player_url": "https://livestreaming.dyte.io:5443/LiveApp/play.html?name=850340555635017830461318",
                            "status": "OFFLINE",
                            "hls_play_url": "https://livestreaming.dyte.io:5443/LiveApp/streams/850340555635017830461318.m3u8"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "LiveStreams"
        ]
      }
    },
    "/livestreams/{streamId}": {
      "get": {
        "summary": "Get a LiveStream",
        "description": "Get details of a particular live stream created by an organization\n",
        "operationId": "GetaLiveStream",
        "parameters": [
          {
            "$ref": "#/components/parameters/streamId"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "success": true,
                      "data": {
                        "id": "850340555635017830461318",
                        "title": "testing",
                        "input_rtmp_url": "rtmp://livestreaming.dyte.io/LiveApp/850340555635017830461318?token=502603528024515256366542",
                        "token_id": "502603528024515256366542",
                        "stream_key": "850340555635017830461318?token=502603528024515256366542",
                        "player_url": "https://livestreaming.dyte.io:5443/LiveApp/play.html?name=850340555635017830461318",
                        "status": "OFFLINE",
                        "hls_play_url": "https://livestreaming.dyte.io:5443/LiveApp/streams/850340555635017830461318.m3u8"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "LiveStreams"
        ]
      }
    },
    "/meetings/{meetingId}/active-session": {
      "get": {
        "summary": "Get an active session",
        "description": "Get an ongoing active session of a meeting",
        "operationId": "GetActiveSession",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/GetActiveSession"
          },
          "404": {
            "$ref": "#/components/responses/GetActiveSessionNotFound"
          }
        }
      }
    },
    "/meetings/{meetingId}/active-session/kick": {
      "post": {
        "summary": "Kick participants from active session",
        "description": "Kick one or more participants using userId or customParticipantId from an active session",
        "operationId": "KickPartcipants",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/KickParticipantsBody"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/KickParticipants"
          },
          "404": {
            "$ref": "#/components/responses/ParticipantNotFound"
          }
        }
      }
    },
    "/meetings/{meetingId}/active-session/kick-all": {
      "post": {
        "summary": "Kick all participant",
        "description": "Kick all participants from an active session",
        "operationId": "KickAllParticipants",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/KickAllParticipants"
          }
        }
      }
    },
    "/meetings/{meetingId}/active-session/mute": {
      "post": {
        "summary": "Mute participants of an active session",
        "description": "Mute one or more participants from an active session using userId or customParticipantId",
        "operationId": "MuteParticipants",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/KickParticipantsBody"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/MuteParticipants"
          }
        }
      }
    },
    "/meetings/{meetingId}/active-session/mute-all": {
      "post": {
        "summary": "Mute all participants",
        "description": "Mute all participants of an active session",
        "operationId": "MuteAllParticipants",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/MuteAllParticipantsBody"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/MuteAllParticipants"
          }
        }
      }
    },
    "/meetings/{meetingId}/active-session/poll": {
      "post": {
        "summary": "Create a poll",
        "description": "Create a new poll in an active session",
        "operationId": "CreatePoll",
        "parameters": [
          {
            "$ref": "#/components/parameters/meetingId"
          }
        ],
        "tags": [
          "ActiveSession"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/CreatePollBody"
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/CreatePoll"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ActiveSession": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "roomUUID of session"
          },
          "associated_id": {
            "type": "string",
            "description": "id of associated object. if session type is meeting, it is mapped to meetingId, livestreamId if session type is livestream"
          },
          "type": {
            "type": "string",
            "description": "type of session",
            "enum": [
              "meeting",
              "livestream",
              "participant"
            ]
          },
          "status": {
            "type": "string",
            "description": "current status of session",
            "enum": [
              "LIVE",
              "ENDED"
            ]
          },
          "live_participants": {
            "type": "number",
            "description": "number of participants currently in the session"
          },
          "max_concurrent_participants": {
            "type": "number",
            "description": "number of maximum participants that were in the session"
          },
          "minutes_consumed": {
            "type": "number",
            "description": "number of minutes consumed since the session started"
          },
          "started_at": {
            "type": "string",
            "description": "timestamp when session started"
          },
          "ended_at": {
            "type": "string",
            "description": "timestamp when session ended"
          },
          "created_at": {
            "type": "string",
            "description": "timestamp when session created"
          },
          "updated_at": {
            "type": "string",
            "description": "timestamp when session was last updated"
          }
        }
      },
      "GenericErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "number"
              },
              "message": {
                "type": "string"
              }
            }
          }
        }
      },
      "Participant": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "picture": {
            "type": "string"
          },
          "verified": {
            "type": "boolean"
          },
          "anonymous": {
            "type": "boolean"
          },
          "allow_mails": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Poll": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "question": {
            "type": "string"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string"
                },
                "count": {
                  "type": "number"
                },
                "votes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          },
          "anonymous": {
            "type": "boolean"
          },
          "hide_votes": {
            "type": "boolean"
          },
          "created_by": {
            "type": "string"
          },
          "voted": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "parameters": {
      "Content-Type": {
        "name": "Content-Type",
        "in": "header",
        "required": true,
        "style": "simple",
        "schema": {
          "type": "string",
          "example": "application/json"
        }
      },
      "streamId": {
        "name": "streamId",
        "in": "path",
        "required": true,
        "style": "simple",
        "schema": {
          "type": "number"
        }
      },
      "meetingId": {
        "name": "meetingId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    },
    "requestBodies": {
      "KickParticipantsBody": {
        "description": "Request body for kicking participants from active session. Only one of `participant_id` or `custom_participant_id` is required",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "participant_ids": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "custom_participant_ids": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      },
      "MuteAllParticipantsBody": {
        "description": "Request body for muting all participants in an active session.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "allow_unmute": {
                  "type": "boolean",
                  "description": "if false, participants won't be able to unmute themselves after they are muted"
                }
              }
            }
          }
        }
      },
      "CreatePollBody": {
        "description": "Request body for creating a new poll",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "question": {
                  "type": "string",
                  "description": "Question of the poll"
                },
                "options": {
                  "type": "array",
                  "description": "Different options for the question",
                  "items": {
                    "type": "string"
                  }
                },
                "anonymous": {
                  "type": "boolean",
                  "description": "if voters on a poll are anonymous"
                },
                "hide_votes": {
                  "type": "boolean",
                  "description": "if votes on an option are visible before a person votes"
                }
              }
            }
          }
        }
      }
    },
    "responses": {
      "GetActiveSession": {
        "description": "Active Session Success response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "$ref": "#/components/schemas/ActiveSession"
                }
              }
            },
            "examples": {
              "activeSessionSuccess": {
                "$ref": "#/components/examples/GetActiveSessionSuccessResponse"
              }
            }
          }
        }
      },
      "GetActiveSessionNotFound": {
        "description": "Active Session is not found for the given meetingId",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GenericErrorResponse"
            },
            "examples": {
              "activeSessionNotFound": {
                "$ref": "#/components/examples/GetActiveSessionNotFoundResponse"
              }
            }
          }
        }
      },
      "KickParticipants": {
        "description": "Kick participants success response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "participants": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Participant"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "ParticipantNotFound": {
        "description": "No participant found for given `participant_id` or `custom_participant_id`",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GenericErrorResponse"
            },
            "examples": {
              "participantNotFound": {
                "$ref": "#/components/examples/ParticipantNotFoundResponse"
              }
            }
          }
        }
      },
      "KickAllParticipants": {
        "description": "Kick all participants from a meeeting",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "kicked_participants_count": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "MuteParticipants": {
        "description": "Mute one or more participants of a meeting",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "participants": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Participant"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "MuteAllParticipants": {
        "description": "Mute all participants of a meeting",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "muted_participants_count": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "CreatePoll": {
        "description": "response for creating a poll",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "success": {
                  "type": "boolean"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "action": {
                      "type": "string"
                    },
                    "poll": {
                      "$ref": "#/components/schemas/Poll"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "examples": {
      "GetActiveSessionSuccessResponse": {
        "summary": "Success response for fetching active session",
        "value": {
          "success": true,
          "data": {
            "id": "813432c7-3c5a-45e2-9acf-eef7061c7584",
            "associated_id": "6bf2b8be-04dd-4191-b602-1128921a306b",
            "type": "meeting",
            "status": "LIVE",
            "live_participants": 1,
            "max_concurrent_participants": 2,
            "minutes_consumed": 2.3434,
            "started_at": "2022-01-12T14:21:34.388Z",
            "ended_at": "null",
            "created_at": "2022-01-12T14:21:34.398Z",
            "updated_at": "2022-01-12T14:26:00.784Z"
          }
        }
      },
      "GetActiveSessionNotFoundResponse": {
        "summary": "Active Session not found",
        "value": {
          "success": false,
          "error": {
            "code": 404,
            "message": "No active session found for meeting_id 6bf2b8be-04dd-4191-b602-1128921a306b"
          }
        }
      },
      "ParticipantNotFoundResponse": {
        "summary": "Participant Not Found",
        "value": {
          "success": false,
          "error": {
            "code": 404,
            "message": "No user found with id 813432c7-3c5a-45e2-9acf-eef7061c7584"
          }
        }
      }
    },
    "securitySchemes": {
      "Authorization": {
        "type": "http",
        "scheme": "basic",
        "description": ""
      }
    }
  },
  "security": [],
  "tags": [
    {
      "name": "LiveStreams"
    },
    {
      "name": "ActiveSession"
    }
  ],
  "externalDocs": {
    "url": "",
    "description": ""
  }
}